### ISSUE TITLE
Import using JSON Folder is out of order

### ISSUE THREAD

**Issue by damonseeley** [thomasloupe/Slackord#52]
Slackord 2 v2.4.5 on Win10

I'm trying to import a small number of JSON files from a single folder to a channel. It works, but some of the messages are posted out of order. For example in a list of files like this...

```
2020-10-21.json
2021-04-08.json
2021-04-21.json
2021-04-22.json
2021-05-21.json
2021-05-22.json
2022-06-14.json
```

The 5/22/21 posts are inserted right after the 10/21/20 posts, and then it proceeds in the correct order.

**Comment by thomasloupe** [comment]
Hi @damonseeley,

I've seen a couple other reports of this. I'm looking into the issue. For now, even though it may be a bit tedious, you may choose to import them one by one, while I work on the solution.

**Comment by thomasloupe** [comment]
https://github.com/thomasloupe/Slackord2/commit/7894dec8bd310aecfddc16df080bae4d6598d191

**Comment by thomasloupe** [comment]
I believe I have fixed this issue. Could you please try and test the latest version here for me and let me know if it's been resolved?
https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.6

Thank you!

**Comment by damonseeley** [comment]
Just verified - it works as expected. Thanks!

**Comment by gka** [comment]
Hi, I am importing a Slack export using Slackord 4.2.2 on Mac and, unfortunately, I still see messages being imported in the wrong order.

**Comment by Kinetic-Gaming** [comment]
Hi Thomas,

Apparently you have even bigger issues if you are emailing your work
problems to random people on the Internet?

However, we do have many programmer's that may be able to solve
your problem in our Discord server.

What project are you working on?

**Comment by thomasloupe** [comment]
@gka Could you please give me an example of this happening.
JSON, etc.

Thanks.

**Comment by thomasloupe** [comment]
@Kinetic-Gaming I am unsure what you mean by your statement here. Emailing work problems? Could you explain?

This project is open sourced.
If anyone wishes to contribute, they are certainly free to!

**Comment by Kinetic-Gaming** [comment]
Thank you for the clarification. My mistake. Sorry for my confusion. 🙏
