### ISSUE TITLE
Slackord immediately crashes or closes on MacOS 13.2.1

### ISSUE THREAD

**Issue by 8bitgentleman** [thomasloupe/Slackord#56]
Hello, I am trying to run this on MacoS 13.2.1. I have set up the permissions and the bot as per the instructions (had to add one step in discord as suggested [here](https://github.com/thomasloupe/Slackord2/issues/51#issuecomment-1438405936) ). When I run Slacord2 it asks for my bot token and then there are 2 options:  Import Slack channels to Discord or Import Slack messages. 

Running the first returns "Unhandled exception." and Slackord crashes. Running the second creates a Files directory where I put a .json file to test.
<img width="264" alt="image" src="https://user-images.githubusercontent.com/4028391/228674520-f0a9a50b-d567-461e-ac30-4d84a28b9a99.png">

Running option 2 again Slackord begins to parse the json and then crashes, seemingly doing nothing. Feels like I'm missing a step here or there is some bug. Any suggestions?

<img width="307" alt="image" src="https://user-images.githubusercontent.com/4028391/228674679-fa25faf3-bbda-46ae-9e80-b3792aa43482.png">

**Comment by thomasloupe** [comment]
Have you tried removing the `place_json_files_here.txt` file? I wonder if it is trying to read an empty text file.
Can you shoot me a DM on Twitter with the json file you're using and I can debug where it's failing. That'll give me a good idea of where to go.

For the channels part, you need to have a `channels.json` file present inside the folder or it will error out. I suppose I could look into better error handling for that as well.

**Comment by 8bitgentleman** [comment]
@thomasloupe  wow that was fast, just DM'd you on twitter with a link to both my `channels.json` and the regular slack export .json file I used. No luck removing the `place_json_files_here.txt` file and even adding the `channels.json` file to the folder still resulted in the same error

**Comment by thomasloupe** [comment]
Thanks for shooting it my way!
I'll have a look at it within the next two hours and see what I can come up with.

**Comment by thomasloupe** [comment]
Please try the latest build and let me know how it goes!
https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.7

**Comment by 8bitgentleman** [comment]
Getting closer, it's chugging along adding messages to the channel!  Only issues I've run into so far

1. Importing slack channels seems to work but checking discord only the first channel, 'general', is imported
2. When it finishes importing Slackord throws an error, even though it's all finished
`Error encountered posting messages: Object reference not set to an instance of an object.`

Other than that things are working smoothly!  
Would be a nice-to-have if you could associate a message from a slack user with the correct discord user

**Comment by thomasloupe** [comment]
If you are available for a Discord chat, please DM me on Twitter and we can have a look at it together when you have a moment. I was able to import all channels from the `channels.json` file with no issues.

For 2, we will need to see where it's happening and i can debug it.

**Comment by thomasloupe** [comment]
Actually, I was able to reproduce the error with 2.
The error is happening because of the `FollowUpAsync` function for Discord. This prevents `The application did not respond` issue that's already been fixed in Windows. I'll put a fix out for this now.

**Comment by thomasloupe** [comment]
I have fixed issue 2 in the latest [release](https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.8).
Issue 1 I am not able to reproduce. It works for me every time I attempt to import channels.

**Comment by thomasloupe** [comment]
For issue number 1. Place the `channels.json` file just outside the `Files` directory and try again.

**Comment by 8bitgentleman** [comment]
#2 looks fixed in the latest, thank you! Just DM'd you my discord username for when you have time

**Comment by thomasloupe** [comment]
Channel importing is now fixed in:
https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.8.2

**Comment by 8bitgentleman** [comment]
Works like a charm, thanks so much!

**Comment by gka** [comment]
I am importing a Slack archive using Slackord 4.2.2 and, unfortunately, I still see messages being imported in the wrong order.
